// <auto-generated />
using System;
using ExpenseApprovalSystem.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseApprovalSystem.Infrastructure.EF.Migrations
{
    [DbContext(typeof(ExpenseApprovalDbContext))]
    [Migration("20251124143437_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.ApprovalStep", b =>
                {
                    b.Property<int>("ApprovalStepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalStepID"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ApprovalStepID");

                    b.HasIndex("ApproverId");

                    b.HasIndex("ExpenseRequestId");

                    b.ToTable("ApprovalSteps", (string)null);

                    b.HasData(
                        new
                        {
                            ApprovalStepID = 1,
                            ApproverId = 2,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpenseRequestId = 1,
                            Status = 0,
                            StepNumber = 1,
                            Type = 0
                        },
                        new
                        {
                            ApprovalStepID = 2,
                            ApproverId = 4,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpenseRequestId = 1,
                            Status = 0,
                            StepNumber = 2,
                            Type = 1
                        },
                        new
                        {
                            ApprovalStepID = 3,
                            ActionDate = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApproverId = 2,
                            CreatedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpenseRequestId = 2,
                            Status = 1,
                            StepNumber = 1,
                            Type = 0
                        },
                        new
                        {
                            ApprovalStepID = 4,
                            ActionDate = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApproverId = 4,
                            CreatedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpenseRequestId = 2,
                            Status = 1,
                            StepNumber = 2,
                            Type = 1
                        },
                        new
                        {
                            ApprovalStepID = 5,
                            ActionDate = new DateTime(2024, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApproverId = 4,
                            Comment = "Budget exceeded",
                            CreatedAt = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpenseRequestId = 3,
                            Status = 2,
                            StepNumber = 1,
                            Type = 1
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            Code = "FIN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            DepartmentID = 2,
                            Code = "HR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            DepartmentID = 3,
                            Code = "ENG",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.ExpenseAttachment", b =>
                {
                    b.Property<int>("ExpenseAttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseAttachmentID"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseRequestId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("ExpenseAttachmentID");

                    b.HasIndex("ExpenseRequestId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("ExpenseAttachments", (string)null);

                    b.HasData(
                        new
                        {
                            ExpenseAttachmentID = 1,
                            ContentType = "application/pdf",
                            ExpenseRequestId = 1,
                            FileName = "flight.pdf",
                            FilePath = "/files/receipts/flight.pdf",
                            FileSize = 245678L,
                            IsDeleted = false,
                            UploadedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UploadedBy = 1
                        },
                        new
                        {
                            ExpenseAttachmentID = 2,
                            ContentType = "application/pdf",
                            ExpenseRequestId = 1,
                            FileName = "hotel.pdf",
                            FilePath = "/files/receipts/hotel.pdf",
                            FileSize = 156789L,
                            IsDeleted = false,
                            UploadedAt = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            UploadedBy = 1
                        },
                        new
                        {
                            ExpenseAttachmentID = 3,
                            ContentType = "image/jpeg",
                            ExpenseRequestId = 2,
                            FileName = "lunch.jpg",
                            FilePath = "/files/receipts/lunch.jpg",
                            FileSize = 56789L,
                            IsDeleted = false,
                            UploadedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UploadedBy = 1
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.ExpenseRequest", b =>
                {
                    b.Property<int>("ExpenseRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseRequestID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ExpenseRequestID");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ExpenseRequests", (string)null);

                    b.HasData(
                        new
                        {
                            ExpenseRequestID = 1,
                            Amount = 250.00m,
                            Category = "Travel",
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Currency = "USD",
                            Description = "Client visit flight tickets",
                            EmployeeId = 1,
                            ExpenseDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = 0
                        },
                        new
                        {
                            ExpenseRequestID = 2,
                            Amount = 120.50m,
                            Category = "Meals",
                            CreatedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Currency = "USD",
                            Description = "Team lunch with partners",
                            EmployeeId = 1,
                            ExpenseDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = 4,
                            UpdatedAt = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = 2
                        },
                        new
                        {
                            ExpenseRequestID = 3,
                            Amount = 980.00m,
                            Category = "Equipment",
                            CreatedAt = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 2,
                            Currency = "USD",
                            Description = "New developer laptop",
                            EmployeeId = 2,
                            ExpenseDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = 5,
                            UpdatedAt = new DateTime(2024, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = 4
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.RequestLog", b =>
                {
                    b.Property<int>("RequestLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestLogID"));

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ExpenseRequestId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestLogID");

                    b.HasIndex("ExpenseRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestLogs", (string)null);

                    b.HasData(
                        new
                        {
                            RequestLogID = 1,
                            ActionBy = "Alice Johnson",
                            ActionDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActionType = 0,
                            Description = "Request submitted",
                            ExpenseRequestId = 1,
                            NewValue = "Pending",
                            UserId = 1
                        },
                        new
                        {
                            RequestLogID = 2,
                            ActionBy = "Alice Johnson",
                            ActionDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActionType = 0,
                            Description = "Request submitted",
                            ExpenseRequestId = 2,
                            NewValue = "Pending",
                            UserId = 1
                        },
                        new
                        {
                            RequestLogID = 3,
                            ActionBy = "Brian Smith",
                            ActionDate = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActionType = 2,
                            Description = "Manager approval",
                            ExpenseRequestId = 2,
                            NewValue = "Approved",
                            OldValue = "Pending",
                            UserId = 2
                        },
                        new
                        {
                            RequestLogID = 4,
                            ActionBy = "Brian Smith",
                            ActionDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActionType = 0,
                            Description = "Request submitted",
                            ExpenseRequestId = 3,
                            NewValue = "Pending",
                            UserId = 2
                        },
                        new
                        {
                            RequestLogID = 5,
                            ActionBy = "David Chen",
                            ActionDate = new DateTime(2024, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActionType = 3,
                            Description = "Cap exceeded",
                            ExpenseRequestId = 3,
                            NewValue = "Rejected",
                            OldValue = "Pending",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "alice@company.com",
                            IsActive = true,
                            NameSurname = "Alice Johnson",
                            PasswordHash = "demo",
                            Role = 0
                        },
                        new
                        {
                            UserID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "brian@company.com",
                            IsActive = true,
                            NameSurname = "Brian Smith",
                            PasswordHash = "demo",
                            Role = 1
                        },
                        new
                        {
                            UserID = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "catherine@company.com",
                            IsActive = true,
                            NameSurname = "Catherine Lee",
                            PasswordHash = "demo",
                            Role = 1
                        },
                        new
                        {
                            UserID = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "david@company.com",
                            IsActive = true,
                            NameSurname = "David Chen",
                            PasswordHash = "demo",
                            Role = 2
                        },
                        new
                        {
                            UserID = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "emma@company.com",
                            IsActive = true,
                            NameSurname = "Emma Davis",
                            PasswordHash = "demo",
                            Role = 3
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.ApprovalStep", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.User", "Approver")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.ExpenseRequest", "ExpenseRequest")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("ExpenseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("ExpenseRequest");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.Department", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.Department", null)
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.ExpenseAttachment", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.ExpenseRequest", "ExpenseRequest")
                        .WithMany("ExpenseAttachments")
                        .HasForeignKey("ExpenseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseRequest");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.ExpenseRequest", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.User", "Employee")
                        .WithMany("ExpenseRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.RequestLog", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.ExpenseRequest", "ExpenseRequest")
                        .WithMany("RequestLogs")
                        .HasForeignKey("ExpenseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.User", "User")
                        .WithMany("RequestLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.Department", b =>
                {
                    b.Navigation("SubDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.ExpenseRequest", b =>
                {
                    b.Navigation("ApprovalSteps");

                    b.Navigation("ExpenseAttachments");

                    b.Navigation("RequestLogs");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("ApprovalSteps");

                    b.Navigation("ExpenseRequests");

                    b.Navigation("RequestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
